### ISSUE TITLE
if add ItemPermission is specified but the permission does not allow it, an empty "add" item is added to the dictionarry 

### ISSUE THREAD

**Issue by decosterkevin** [intellineers/django-bridger#106]
This leads to the frontend understanding that it needs to display the add button because the key `add` is present in the option dictionary.

I believe this should be the responsibility of the backend to ensure that none empty item are added to the option

**Comment by decosterkevin** [comment]
Example if an employee is not allowed to add a department, the returns menu option is as follow:
```
{
    "label":"Department",
    "items":[
        {
            "label":"Positions",
            "endpoint":"http://0.0.0.0:5000/api/human_resources/position/",
            "add":{
                
            }
        }
    ]
}
```

I believe it should be:
```
{
    "label":"Department",
    "items":[
        {
            "label":"Positions",
            "endpoint":"http://0.0.0.0:5000/api/human_resources/position/"
        }
    ]
}
```

**Comment by cwittlinger** [comment]
I see - That should in fact not be possible. I just think we should check below if add is empty.

https://github.com/intellineers/django-bridger/blob/010d8d6c5c9a04041c479bdee3714e2754f3c418/bridger/menus/menus.py#L56-L58
