### ISSUE TITLE
Since the latest django-filters, filter_fields attribute is depreciated for filterset_fields

### ISSUE THREAD

**Issue by loickouao** [intellineers/django-bridger#19]
Warning `filter_fields` attribute of viewsets  should be renamed `filterset_fields`.

**Comment by cw-intellineers** [comment]
Yes I know. Should not be an issue to change that I guess? Otherwise I can revert to the previous version django-filters. @decosterkevin you see any issue here?

**Comment by decosterkevin** [comment]
Should be fine. I guess there is some reference to filter_fields in the wb, but nothing a quick refactor could handle
