### ISSUE TITLE
Endpoints should enforce routing

### ISSUE THREAD

**Issue by decosterkevin** [intellineers/django-bridger#20]
When setting endpoints to `None`, `BridgerRouter` should not include the action.

**List (`url/`)**
* `instance_endpoint` -> Forbid GET `url/<pk>/`
* `list_endpoint` -> Nothing happens
* `create_endpoint` -> Forbid CREATE `url/`
* `delete_endpoint` -> Forbid DELETE `url/`

**Instance (`url/<pk>/`)**
* `instance_endpoint` -> Forbid PATCH/PUT `url/<pk>/`
* `list_endpoint` -> Nothing happens
* `create_endpoint` -> Forbid CREATE `url/`
* `delete_endpoint` -> Forbid DELETE `url/<pk>/`

**Comment by cw-intellineers** [comment]
That makes sense, I will think about it.
