### ISSUE TITLE
Buttons / Endpoints

### ISSUE THREAD

**Issue by cwittlinger** [intellineers/django-bridger#44]
Currently we define default buttons like this:
```json
"buttons": ["create", "refresh"]
```
And endpoints like this:
```json
"endpoints": {
   "create": "some_endpoint"
}
```
Defining one without the other leads to a lot of questions, e.g.:
* If I define the button, but no endpoint, what happens?
* If I define the endpoint, but no button, what happens?

At the moment, we use the "instance" identifier in endpoints to determine whether a row in a list is clickable, if the "instance" endpoint is `null` or non existent, the row is just not clickable anymore. Maybe it is a good idea to copy this behaviour to all other things as well. Currently we have the following buttons, which you could be mapped to the following endpoints:

**In List Views:**
* create -> create_endpoint
* delete -> delete_endpoint **(Batch delete, to be implemented)**

**In Instance Views:**
* delete -> delete_endpoint
* save -> instance_endpoint

Refresh/Reset is always enabled.

By doing this, we would get rid of the "buttons" list and only have one way to define them. Furthermore it is easier to solve #20, because we only have to do it in one place.

**Comment by cwittlinger** [comment]
@decosterkevin @cs-intellineers What do you guys think about this?

**Comment by cs-intellineers** [comment]
In general I am in favor of this. This means less configuration we have to maintain.

However, you have to be aware that you will loose some control. For instance, you can't have an instance form without a save button while having a refresh button then.
As long as you (i.e. the backend) are fine with this, we can do this.

**Comment by cwittlinger** [comment]
That is actually true, I did not think about this. What we could say is that Refresh is always available (since you have ended up somehow at this resource you should always be able to refresh that resource. That obviously means that you cannot disable the refresh button, which i believe is fine as there are no widgets that I know of that disabled this button.

**Comment by decosterkevin** [comment]
I agree with this as well, there is no real reason to have a "save" button but the create endpoint disable. Furthermore, it would be easier to ensure that POST request on view without create endpoint returns 404, which is not the case at the moment.

There are few views where we set permission based user just by disabling the "save" button for instance

**Comment by cwittlinger** [comment]
@decosterkevin This is what I meant with this will lead to easier solution for #20. What do you think about making the refresh button mandatory?

**Comment by decosterkevin** [comment]
I believe it does make sense to have it mandatory. I don't think there is anywhere where we don't have it

**Comment by cwittlinger** [comment]
**So to summerize, we agree on the following:**
* Refresh is mandatory for List/Instance, Reset is mandatory for Create
* We only define endpoints, where the frontend can infer what buttons to display
