### ISSUE TITLE
PK_FIELD is not included in the option request anymore

### ISSUE THREAD

**Issue by decosterkevin** [intellineers/django-bridger#51]
the pk field is set to null in the option request, even though the ViewSet defines it otherwise.

eg: CalendarViewset

**Comment by cwittlinger** [comment]
I will take a look.

**Comment by cwittlinger** [comment]
The PK_FIELD needs to be set in the EndpointConfig, not the Viewset. I adjusted it in the CalendarEndpointConfig.
