### ISSUE TITLE
AttributeError: 'User' object has no attribute 'first_name'

### ISSUE THREAD

**Issue by loickouao** [intellineers/django-bridger#84]
'User' object has no attribute 'first_name' and 'last_name'
I am wrong or should not be replaced in bridger / views.py 

```
def get_user_name(request):
    return f'{request.user.first_name} {request.user.last_name}'
```

By

```
def get_user_name(request):
    return f'{request.user.profile.first_name} {request.user.profile.last_name}'
```

**Comment by cwittlinger** [comment]
Not really - because Kevin Removed the first and last name in wbauth, therefore this package has to take of it. Bridger does not know anything about a profile. I think the easiest solution would be to create two properties in the UserModel:

```python
@property
def first_name(self):
   return self.profile.first_name

@property
def last_name(self):
   return self.profile.last_name
```

**Comment by loickouao** [comment]
Yes can do it, I must just add the property in the User Model from wbauthentication
```
class User(EmailAbstractUser):

          @property
          def first_name(self):
             return self.profile.first_name
          
          @property
          def last_name(self):
             return self.profile.last_name
```

**Comment by loickouao** [comment]
Mais je remarque que Kevin  override la fonction get_user_name in the settings 

and dans les settings de bridger :
DEFAULT_USER_NAME": "tests.settings.get_user_name",

**Comment by loickouao** [comment]
yes, it's fine. Thank you

**Comment by cwittlinger** [comment]
I still believe we should include the `first_name` and `last_name` property in the user model.

**Comment by loickouao** [comment]
yes I also think it's better, to avoid possible errors related to this, I will do it

**Comment by cwittlinger** [comment]
Thanks @loickouao for taking care - Close this issue once done please
