### ISSUE TITLE
Fix broken views

### ISSUE THREAD

**Issue by cwittlinger** [intellineers/django-bridger#96]

**Comment by cwittlinger** [comment]
@loickouao What is the state of this?

**Comment by loickouao** [comment]
Always not fixed, I try to understand why  field type 'markdowneditor'! is Unknown

**Comment by cwittlinger** [comment]
markdowneditor does not exist anymore. just change it to texteditor.

**Comment by cwittlinger** [comment]
@loickouao You think you will finish it today?

**Comment by loickouao** [comment]
Yes I think today afternoon it should be good

**Comment by cwittlinger** [comment]
Perfect - Just create the PR once done and I will check everything tonight.

**Comment by loickouao** [comment]
@cwittlinger since the view does not have a model, content_return None, so I modify the get_content_type method
![image](https://user-images.githubusercontent.com/32362060/121342194-b1431780-c921-11eb-9c4c-3117bb5ecf0b.png)
